name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
  - type: input
    id: obsi-version
    attributes:
      label: Obsidian Version
      description: You can find the version in the *About* Tab of the settings.
      placeholder: 0.13.19
    validations:
      required: true
  - type: checkboxes
    id: editor
    attributes:
      label: Which editor are you using?
      description: If you are using the Legacy Editor, please be aware thare are some smaller issues with punctuations at the border of a word. Due to the Legacy Editor being deprecated, it is unfortunately not worth the effort to code fixes for that.
      options:
        - label: New Editor
        - label: Legacy Editor
  - type: checkboxes
    id: mode
    attributes:
      label: In which mode(s) does the problem occur?
      options:
        - label: Source (Edit)
        - label: Live Preview
        - label: Reading (Preview)
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I updated to the latest version of the plugin.
          required: true

